version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: usermgmt-postgres
    environment:
      POSTGRES_DB: pocdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build: .
    container_name: usermgmt-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pocdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      JWT_SECRET: Pa8QFmbk/9BR33m+K6ischX4VEoyJ0DM3JlB3hf0uuw=
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
